//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 The provider-azure-adx Authors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/functional-team/provider-azure-adx/apis/common"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CalloutPolicy) DeepCopyInto(out *CalloutPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CalloutPolicy.
func (in *CalloutPolicy) DeepCopy() *CalloutPolicy {
	if in == nil {
		return nil
	}
	out := new(CalloutPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CalloutPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CalloutPolicyList) DeepCopyInto(out *CalloutPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CalloutPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CalloutPolicyList.
func (in *CalloutPolicyList) DeepCopy() *CalloutPolicyList {
	if in == nil {
		return nil
	}
	out := new(CalloutPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CalloutPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CalloutPolicyParameters) DeepCopyInto(out *CalloutPolicyParameters) {
	*out = *in
	if in.Callouts != nil {
		in, out := &in.Callouts, &out.Callouts
		*out = make([]CalloutRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CalloutPolicyParameters.
func (in *CalloutPolicyParameters) DeepCopy() *CalloutPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(CalloutPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CalloutPolicySpec) DeepCopyInto(out *CalloutPolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CalloutPolicySpec.
func (in *CalloutPolicySpec) DeepCopy() *CalloutPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CalloutPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CalloutPolicyStatus) DeepCopyInto(out *CalloutPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CalloutPolicyStatus.
func (in *CalloutPolicyStatus) DeepCopy() *CalloutPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(CalloutPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CalloutRule) DeepCopyInto(out *CalloutRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CalloutRule.
func (in *CalloutRule) DeepCopy() *CalloutRule {
	if in == nil {
		return nil
	}
	out := new(CalloutRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPolicy) DeepCopyInto(out *CapacityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPolicy.
func (in *CapacityPolicy) DeepCopy() *CapacityPolicy {
	if in == nil {
		return nil
	}
	out := new(CapacityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CapacityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPolicyList) DeepCopyInto(out *CapacityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CapacityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPolicyList.
func (in *CapacityPolicyList) DeepCopy() *CapacityPolicyList {
	if in == nil {
		return nil
	}
	out := new(CapacityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CapacityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPolicyParameters) DeepCopyInto(out *CapacityPolicyParameters) {
	*out = *in
	in.Policy.DeepCopyInto(&out.Policy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPolicyParameters.
func (in *CapacityPolicyParameters) DeepCopy() *CapacityPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(CapacityPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPolicySpec) DeepCopyInto(out *CapacityPolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPolicySpec.
func (in *CapacityPolicySpec) DeepCopy() *CapacityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CapacityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPolicyStatus) DeepCopyInto(out *CapacityPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPolicyStatus.
func (in *CapacityPolicyStatus) DeepCopy() *CapacityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(CapacityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterManagedIdentityEntry) DeepCopyInto(out *ClusterManagedIdentityEntry) {
	*out = *in
	if in.AllowedUsages != nil {
		in, out := &in.AllowedUsages, &out.AllowedUsages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterManagedIdentityEntry.
func (in *ClusterManagedIdentityEntry) DeepCopy() *ClusterManagedIdentityEntry {
	if in == nil {
		return nil
	}
	out := new(ClusterManagedIdentityEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterManagedIdentityPolicy) DeepCopyInto(out *ClusterManagedIdentityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterManagedIdentityPolicy.
func (in *ClusterManagedIdentityPolicy) DeepCopy() *ClusterManagedIdentityPolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterManagedIdentityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterManagedIdentityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterManagedIdentityPolicyList) DeepCopyInto(out *ClusterManagedIdentityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterManagedIdentityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterManagedIdentityPolicyList.
func (in *ClusterManagedIdentityPolicyList) DeepCopy() *ClusterManagedIdentityPolicyList {
	if in == nil {
		return nil
	}
	out := new(ClusterManagedIdentityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterManagedIdentityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterManagedIdentityPolicyParameters) DeepCopyInto(out *ClusterManagedIdentityPolicyParameters) {
	*out = *in
	if in.Identities != nil {
		in, out := &in.Identities, &out.Identities
		*out = make([]ClusterManagedIdentityEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterManagedIdentityPolicyParameters.
func (in *ClusterManagedIdentityPolicyParameters) DeepCopy() *ClusterManagedIdentityPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(ClusterManagedIdentityPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterManagedIdentityPolicySpec) DeepCopyInto(out *ClusterManagedIdentityPolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterManagedIdentityPolicySpec.
func (in *ClusterManagedIdentityPolicySpec) DeepCopy() *ClusterManagedIdentityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterManagedIdentityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterManagedIdentityPolicyStatus) DeepCopyInto(out *ClusterManagedIdentityPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterManagedIdentityPolicyStatus.
func (in *ClusterManagedIdentityPolicyStatus) DeepCopy() *ClusterManagedIdentityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterManagedIdentityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPolicyObservation) DeepCopyInto(out *ClusterPolicyObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPolicyObservation.
func (in *ClusterPolicyObservation) DeepCopy() *ClusterPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(ClusterPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiDatabaseAdminsPolicy) DeepCopyInto(out *MultiDatabaseAdminsPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiDatabaseAdminsPolicy.
func (in *MultiDatabaseAdminsPolicy) DeepCopy() *MultiDatabaseAdminsPolicy {
	if in == nil {
		return nil
	}
	out := new(MultiDatabaseAdminsPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultiDatabaseAdminsPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiDatabaseAdminsPolicyList) DeepCopyInto(out *MultiDatabaseAdminsPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MultiDatabaseAdminsPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiDatabaseAdminsPolicyList.
func (in *MultiDatabaseAdminsPolicyList) DeepCopy() *MultiDatabaseAdminsPolicyList {
	if in == nil {
		return nil
	}
	out := new(MultiDatabaseAdminsPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultiDatabaseAdminsPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiDatabaseAdminsPolicyParameters) DeepCopyInto(out *MultiDatabaseAdminsPolicyParameters) {
	*out = *in
	if in.Principals != nil {
		in, out := &in.Principals, &out.Principals
		*out = make([]common.Principal, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiDatabaseAdminsPolicyParameters.
func (in *MultiDatabaseAdminsPolicyParameters) DeepCopy() *MultiDatabaseAdminsPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(MultiDatabaseAdminsPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiDatabaseAdminsPolicySpec) DeepCopyInto(out *MultiDatabaseAdminsPolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiDatabaseAdminsPolicySpec.
func (in *MultiDatabaseAdminsPolicySpec) DeepCopy() *MultiDatabaseAdminsPolicySpec {
	if in == nil {
		return nil
	}
	out := new(MultiDatabaseAdminsPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiDatabaseAdminsPolicyStatus) DeepCopyInto(out *MultiDatabaseAdminsPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiDatabaseAdminsPolicyStatus.
func (in *MultiDatabaseAdminsPolicyStatus) DeepCopy() *MultiDatabaseAdminsPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(MultiDatabaseAdminsPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryWeakConsistencyPolicy) DeepCopyInto(out *QueryWeakConsistencyPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryWeakConsistencyPolicy.
func (in *QueryWeakConsistencyPolicy) DeepCopy() *QueryWeakConsistencyPolicy {
	if in == nil {
		return nil
	}
	out := new(QueryWeakConsistencyPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueryWeakConsistencyPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryWeakConsistencyPolicyList) DeepCopyInto(out *QueryWeakConsistencyPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QueryWeakConsistencyPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryWeakConsistencyPolicyList.
func (in *QueryWeakConsistencyPolicyList) DeepCopy() *QueryWeakConsistencyPolicyList {
	if in == nil {
		return nil
	}
	out := new(QueryWeakConsistencyPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueryWeakConsistencyPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryWeakConsistencyPolicyParameters) DeepCopyInto(out *QueryWeakConsistencyPolicyParameters) {
	*out = *in
	if in.PercentageOfNodes != nil {
		in, out := &in.PercentageOfNodes, &out.PercentageOfNodes
		*out = new(int64)
		**out = **in
	}
	if in.MinimumNumberOfNodes != nil {
		in, out := &in.MinimumNumberOfNodes, &out.MinimumNumberOfNodes
		*out = new(int64)
		**out = **in
	}
	if in.MaximumNumberOfNodes != nil {
		in, out := &in.MaximumNumberOfNodes, &out.MaximumNumberOfNodes
		*out = new(int64)
		**out = **in
	}
	if in.SuperSlackerNumberOfNodesThreshold != nil {
		in, out := &in.SuperSlackerNumberOfNodesThreshold, &out.SuperSlackerNumberOfNodesThreshold
		*out = new(int64)
		**out = **in
	}
	if in.EnableMetadataPrefetch != nil {
		in, out := &in.EnableMetadataPrefetch, &out.EnableMetadataPrefetch
		*out = new(bool)
		**out = **in
	}
	if in.MaximumLagAllowedInMinutes != nil {
		in, out := &in.MaximumLagAllowedInMinutes, &out.MaximumLagAllowedInMinutes
		*out = new(int64)
		**out = **in
	}
	if in.RefreshPeriodInSeconds != nil {
		in, out := &in.RefreshPeriodInSeconds, &out.RefreshPeriodInSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryWeakConsistencyPolicyParameters.
func (in *QueryWeakConsistencyPolicyParameters) DeepCopy() *QueryWeakConsistencyPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(QueryWeakConsistencyPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryWeakConsistencyPolicySpec) DeepCopyInto(out *QueryWeakConsistencyPolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryWeakConsistencyPolicySpec.
func (in *QueryWeakConsistencyPolicySpec) DeepCopy() *QueryWeakConsistencyPolicySpec {
	if in == nil {
		return nil
	}
	out := new(QueryWeakConsistencyPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryWeakConsistencyPolicyStatus) DeepCopyInto(out *QueryWeakConsistencyPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryWeakConsistencyPolicyStatus.
func (in *QueryWeakConsistencyPolicyStatus) DeepCopy() *QueryWeakConsistencyPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(QueryWeakConsistencyPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestClassificationPolicy) DeepCopyInto(out *RequestClassificationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestClassificationPolicy.
func (in *RequestClassificationPolicy) DeepCopy() *RequestClassificationPolicy {
	if in == nil {
		return nil
	}
	out := new(RequestClassificationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RequestClassificationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestClassificationPolicyList) DeepCopyInto(out *RequestClassificationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RequestClassificationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestClassificationPolicyList.
func (in *RequestClassificationPolicyList) DeepCopy() *RequestClassificationPolicyList {
	if in == nil {
		return nil
	}
	out := new(RequestClassificationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RequestClassificationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestClassificationPolicyParameters) DeepCopyInto(out *RequestClassificationPolicyParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestClassificationPolicyParameters.
func (in *RequestClassificationPolicyParameters) DeepCopy() *RequestClassificationPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(RequestClassificationPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestClassificationPolicySpec) DeepCopyInto(out *RequestClassificationPolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestClassificationPolicySpec.
func (in *RequestClassificationPolicySpec) DeepCopy() *RequestClassificationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RequestClassificationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestClassificationPolicyStatus) DeepCopyInto(out *RequestClassificationPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestClassificationPolicyStatus.
func (in *RequestClassificationPolicyStatus) DeepCopy() *RequestClassificationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RequestClassificationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxPolicy) DeepCopyInto(out *SandboxPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxPolicy.
func (in *SandboxPolicy) DeepCopy() *SandboxPolicy {
	if in == nil {
		return nil
	}
	out := new(SandboxPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxPolicyList) DeepCopyInto(out *SandboxPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxPolicyList.
func (in *SandboxPolicyList) DeepCopy() *SandboxPolicyList {
	if in == nil {
		return nil
	}
	out := new(SandboxPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxPolicyParameters) DeepCopyInto(out *SandboxPolicyParameters) {
	*out = *in
	if in.Sandboxes != nil {
		in, out := &in.Sandboxes, &out.Sandboxes
		*out = make([]SandboxRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxPolicyParameters.
func (in *SandboxPolicyParameters) DeepCopy() *SandboxPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(SandboxPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxPolicySpec) DeepCopyInto(out *SandboxPolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxPolicySpec.
func (in *SandboxPolicySpec) DeepCopy() *SandboxPolicySpec {
	if in == nil {
		return nil
	}
	out := new(SandboxPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxPolicyStatus) DeepCopyInto(out *SandboxPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxPolicyStatus.
func (in *SandboxPolicyStatus) DeepCopy() *SandboxPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxRule) DeepCopyInto(out *SandboxRule) {
	*out = *in
	if in.VirtualMachineSize != nil {
		in, out := &in.VirtualMachineSize, &out.VirtualMachineSize
		*out = new(string)
		**out = **in
	}
	if in.InitializeOnStartup != nil {
		in, out := &in.InitializeOnStartup, &out.InitializeOnStartup
		*out = new(bool)
		**out = **in
	}
	if in.MaxNumberOfSandboxes != nil {
		in, out := &in.MaxNumberOfSandboxes, &out.MaxNumberOfSandboxes
		*out = new(int64)
		**out = **in
	}
	if in.MaxCPUPerSandbox != nil {
		in, out := &in.MaxCPUPerSandbox, &out.MaxCPUPerSandbox
		*out = new(int64)
		**out = **in
	}
	if in.MaxMemoryMbPerSandbox != nil {
		in, out := &in.MaxMemoryMbPerSandbox, &out.MaxMemoryMbPerSandbox
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxRule.
func (in *SandboxRule) DeepCopy() *SandboxRule {
	if in == nil {
		return nil
	}
	out := new(SandboxRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadGroup) DeepCopyInto(out *WorkloadGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadGroup.
func (in *WorkloadGroup) DeepCopy() *WorkloadGroup {
	if in == nil {
		return nil
	}
	out := new(WorkloadGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadGroupList) DeepCopyInto(out *WorkloadGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadGroupList.
func (in *WorkloadGroupList) DeepCopy() *WorkloadGroupList {
	if in == nil {
		return nil
	}
	out := new(WorkloadGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadGroupObservation) DeepCopyInto(out *WorkloadGroupObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadGroupObservation.
func (in *WorkloadGroupObservation) DeepCopy() *WorkloadGroupObservation {
	if in == nil {
		return nil
	}
	out := new(WorkloadGroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadGroupParameters) DeepCopyInto(out *WorkloadGroupParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	in.WorkloadGroup.DeepCopyInto(&out.WorkloadGroup)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadGroupParameters.
func (in *WorkloadGroupParameters) DeepCopy() *WorkloadGroupParameters {
	if in == nil {
		return nil
	}
	out := new(WorkloadGroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadGroupSpec) DeepCopyInto(out *WorkloadGroupSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadGroupSpec.
func (in *WorkloadGroupSpec) DeepCopy() *WorkloadGroupSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadGroupStatus) DeepCopyInto(out *WorkloadGroupStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadGroupStatus.
func (in *WorkloadGroupStatus) DeepCopy() *WorkloadGroupStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadGroupStatus)
	in.DeepCopyInto(out)
	return out
}
