//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 The provider-azure-adx Authors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/functional-team/provider-azure-adx/apis/common"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedPrincipal) DeepCopyInto(out *ResolvedPrincipal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedPrincipal.
func (in *ResolvedPrincipal) DeepCopy() *ResolvedPrincipal {
	if in == nil {
		return nil
	}
	out := new(ResolvedPrincipal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityRole) DeepCopyInto(out *SecurityRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityRole.
func (in *SecurityRole) DeepCopy() *SecurityRole {
	if in == nil {
		return nil
	}
	out := new(SecurityRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityRoleList) DeepCopyInto(out *SecurityRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecurityRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityRoleList.
func (in *SecurityRoleList) DeepCopy() *SecurityRoleList {
	if in == nil {
		return nil
	}
	out := new(SecurityRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityRoleObservation) DeepCopyInto(out *SecurityRoleObservation) {
	*out = *in
	if in.ResolvedPrincipals != nil {
		in, out := &in.ResolvedPrincipals, &out.ResolvedPrincipals
		*out = make([]ResolvedPrincipal, len(*in))
		copy(*out, *in)
	}
	if in.Unresolved != nil {
		in, out := &in.Unresolved, &out.Unresolved
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Principals != nil {
		in, out := &in.Principals, &out.Principals
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityRoleObservation.
func (in *SecurityRoleObservation) DeepCopy() *SecurityRoleObservation {
	if in == nil {
		return nil
	}
	out := new(SecurityRoleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityRoleParameters) DeepCopyInto(out *SecurityRoleParameters) {
	*out = *in
	in.Entity.DeepCopyInto(&out.Entity)
	if in.Principals != nil {
		in, out := &in.Principals, &out.Principals
		*out = make([]common.Principal, len(*in))
		copy(*out, *in)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityRoleParameters.
func (in *SecurityRoleParameters) DeepCopy() *SecurityRoleParameters {
	if in == nil {
		return nil
	}
	out := new(SecurityRoleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityRoleSpec) DeepCopyInto(out *SecurityRoleSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityRoleSpec.
func (in *SecurityRoleSpec) DeepCopy() *SecurityRoleSpec {
	if in == nil {
		return nil
	}
	out := new(SecurityRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityRoleStatus) DeepCopyInto(out *SecurityRoleStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityRoleStatus.
func (in *SecurityRoleStatus) DeepCopy() *SecurityRoleStatus {
	if in == nil {
		return nil
	}
	out := new(SecurityRoleStatus)
	in.DeepCopyInto(out)
	return out
}
