//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 The provider-azure-adx Authors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	"github.com/functional-team/provider-azure-adx/apis/common"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoDeletePolicy) DeepCopyInto(out *AutoDeletePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoDeletePolicy.
func (in *AutoDeletePolicy) DeepCopy() *AutoDeletePolicy {
	if in == nil {
		return nil
	}
	out := new(AutoDeletePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoDeletePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoDeletePolicyList) DeepCopyInto(out *AutoDeletePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AutoDeletePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoDeletePolicyList.
func (in *AutoDeletePolicyList) DeepCopy() *AutoDeletePolicyList {
	if in == nil {
		return nil
	}
	out := new(AutoDeletePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoDeletePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoDeletePolicyParameters) DeepCopyInto(out *AutoDeletePolicyParameters) {
	*out = *in
	in.PolicyTarget.DeepCopyInto(&out.PolicyTarget)
	if in.DeleteIfNotEmpty != nil {
		in, out := &in.DeleteIfNotEmpty, &out.DeleteIfNotEmpty
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoDeletePolicyParameters.
func (in *AutoDeletePolicyParameters) DeepCopy() *AutoDeletePolicyParameters {
	if in == nil {
		return nil
	}
	out := new(AutoDeletePolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoDeletePolicySpec) DeepCopyInto(out *AutoDeletePolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoDeletePolicySpec.
func (in *AutoDeletePolicySpec) DeepCopy() *AutoDeletePolicySpec {
	if in == nil {
		return nil
	}
	out := new(AutoDeletePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoDeletePolicyStatus) DeepCopyInto(out *AutoDeletePolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoDeletePolicyStatus.
func (in *AutoDeletePolicyStatus) DeepCopy() *AutoDeletePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AutoDeletePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CachingPolicy) DeepCopyInto(out *CachingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CachingPolicy.
func (in *CachingPolicy) DeepCopy() *CachingPolicy {
	if in == nil {
		return nil
	}
	out := new(CachingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CachingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CachingPolicyList) DeepCopyInto(out *CachingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CachingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CachingPolicyList.
func (in *CachingPolicyList) DeepCopy() *CachingPolicyList {
	if in == nil {
		return nil
	}
	out := new(CachingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CachingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CachingPolicyParameters) DeepCopyInto(out *CachingPolicyParameters) {
	*out = *in
	in.PolicyTarget.DeepCopyInto(&out.PolicyTarget)
	if in.HotWindows != nil {
		in, out := &in.HotWindows, &out.HotWindows
		*out = make([]HotWindow, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CachingPolicyParameters.
func (in *CachingPolicyParameters) DeepCopy() *CachingPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(CachingPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CachingPolicySpec) DeepCopyInto(out *CachingPolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CachingPolicySpec.
func (in *CachingPolicySpec) DeepCopy() *CachingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CachingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CachingPolicyStatus) DeepCopyInto(out *CachingPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CachingPolicyStatus.
func (in *CachingPolicyStatus) DeepCopy() *CachingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(CachingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncodingPolicy) DeepCopyInto(out *EncodingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncodingPolicy.
func (in *EncodingPolicy) DeepCopy() *EncodingPolicy {
	if in == nil {
		return nil
	}
	out := new(EncodingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EncodingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncodingPolicyList) DeepCopyInto(out *EncodingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EncodingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncodingPolicyList.
func (in *EncodingPolicyList) DeepCopy() *EncodingPolicyList {
	if in == nil {
		return nil
	}
	out := new(EncodingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EncodingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncodingPolicyParameters) DeepCopyInto(out *EncodingPolicyParameters) {
	*out = *in
	in.PolicyTarget.DeepCopyInto(&out.PolicyTarget)
	if in.Column != nil {
		in, out := &in.Column, &out.Column
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncodingPolicyParameters.
func (in *EncodingPolicyParameters) DeepCopy() *EncodingPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(EncodingPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncodingPolicySpec) DeepCopyInto(out *EncodingPolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncodingPolicySpec.
func (in *EncodingPolicySpec) DeepCopy() *EncodingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(EncodingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncodingPolicyStatus) DeepCopyInto(out *EncodingPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncodingPolicyStatus.
func (in *EncodingPolicyStatus) DeepCopy() *EncodingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(EncodingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtentTagsRetentionPolicy) DeepCopyInto(out *ExtentTagsRetentionPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtentTagsRetentionPolicy.
func (in *ExtentTagsRetentionPolicy) DeepCopy() *ExtentTagsRetentionPolicy {
	if in == nil {
		return nil
	}
	out := new(ExtentTagsRetentionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExtentTagsRetentionPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtentTagsRetentionPolicyList) DeepCopyInto(out *ExtentTagsRetentionPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExtentTagsRetentionPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtentTagsRetentionPolicyList.
func (in *ExtentTagsRetentionPolicyList) DeepCopy() *ExtentTagsRetentionPolicyList {
	if in == nil {
		return nil
	}
	out := new(ExtentTagsRetentionPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExtentTagsRetentionPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtentTagsRetentionPolicyParameters) DeepCopyInto(out *ExtentTagsRetentionPolicyParameters) {
	*out = *in
	in.PolicyTarget.DeepCopyInto(&out.PolicyTarget)
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]ExtentTagsRetentionRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtentTagsRetentionPolicyParameters.
func (in *ExtentTagsRetentionPolicyParameters) DeepCopy() *ExtentTagsRetentionPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(ExtentTagsRetentionPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtentTagsRetentionPolicySpec) DeepCopyInto(out *ExtentTagsRetentionPolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtentTagsRetentionPolicySpec.
func (in *ExtentTagsRetentionPolicySpec) DeepCopy() *ExtentTagsRetentionPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ExtentTagsRetentionPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtentTagsRetentionPolicyStatus) DeepCopyInto(out *ExtentTagsRetentionPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtentTagsRetentionPolicyStatus.
func (in *ExtentTagsRetentionPolicyStatus) DeepCopy() *ExtentTagsRetentionPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ExtentTagsRetentionPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtentTagsRetentionRule) DeepCopyInto(out *ExtentTagsRetentionRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtentTagsRetentionRule.
func (in *ExtentTagsRetentionRule) DeepCopy() *ExtentTagsRetentionRule {
	if in == nil {
		return nil
	}
	out := new(ExtentTagsRetentionRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotWindow) DeepCopyInto(out *HotWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotWindow.
func (in *HotWindow) DeepCopy() *HotWindow {
	if in == nil {
		return nil
	}
	out := new(HotWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestionBatchingPolicy) DeepCopyInto(out *IngestionBatchingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestionBatchingPolicy.
func (in *IngestionBatchingPolicy) DeepCopy() *IngestionBatchingPolicy {
	if in == nil {
		return nil
	}
	out := new(IngestionBatchingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IngestionBatchingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestionBatchingPolicyList) DeepCopyInto(out *IngestionBatchingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IngestionBatchingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestionBatchingPolicyList.
func (in *IngestionBatchingPolicyList) DeepCopy() *IngestionBatchingPolicyList {
	if in == nil {
		return nil
	}
	out := new(IngestionBatchingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IngestionBatchingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestionBatchingPolicyParameters) DeepCopyInto(out *IngestionBatchingPolicyParameters) {
	*out = *in
	in.PolicyTarget.DeepCopyInto(&out.PolicyTarget)
	if in.MaximumBatchingTimeSpan != nil {
		in, out := &in.MaximumBatchingTimeSpan, &out.MaximumBatchingTimeSpan
		*out = new(common.Timespan)
		**out = **in
	}
	if in.MaximumNumberOfItems != nil {
		in, out := &in.MaximumNumberOfItems, &out.MaximumNumberOfItems
		*out = new(int64)
		**out = **in
	}
	if in.MaximumRawDataSizeMB != nil {
		in, out := &in.MaximumRawDataSizeMB, &out.MaximumRawDataSizeMB
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestionBatchingPolicyParameters.
func (in *IngestionBatchingPolicyParameters) DeepCopy() *IngestionBatchingPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(IngestionBatchingPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestionBatchingPolicySpec) DeepCopyInto(out *IngestionBatchingPolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestionBatchingPolicySpec.
func (in *IngestionBatchingPolicySpec) DeepCopy() *IngestionBatchingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(IngestionBatchingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestionBatchingPolicyStatus) DeepCopyInto(out *IngestionBatchingPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestionBatchingPolicyStatus.
func (in *IngestionBatchingPolicyStatus) DeepCopy() *IngestionBatchingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(IngestionBatchingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestionTimePolicy) DeepCopyInto(out *IngestionTimePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestionTimePolicy.
func (in *IngestionTimePolicy) DeepCopy() *IngestionTimePolicy {
	if in == nil {
		return nil
	}
	out := new(IngestionTimePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IngestionTimePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestionTimePolicyList) DeepCopyInto(out *IngestionTimePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IngestionTimePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestionTimePolicyList.
func (in *IngestionTimePolicyList) DeepCopy() *IngestionTimePolicyList {
	if in == nil {
		return nil
	}
	out := new(IngestionTimePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IngestionTimePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestionTimePolicyParameters) DeepCopyInto(out *IngestionTimePolicyParameters) {
	*out = *in
	in.PolicyTarget.DeepCopyInto(&out.PolicyTarget)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestionTimePolicyParameters.
func (in *IngestionTimePolicyParameters) DeepCopy() *IngestionTimePolicyParameters {
	if in == nil {
		return nil
	}
	out := new(IngestionTimePolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestionTimePolicySpec) DeepCopyInto(out *IngestionTimePolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestionTimePolicySpec.
func (in *IngestionTimePolicySpec) DeepCopy() *IngestionTimePolicySpec {
	if in == nil {
		return nil
	}
	out := new(IngestionTimePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestionTimePolicyStatus) DeepCopyInto(out *IngestionTimePolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestionTimePolicyStatus.
func (in *IngestionTimePolicyStatus) DeepCopy() *IngestionTimePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(IngestionTimePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedIdentityEntry) DeepCopyInto(out *ManagedIdentityEntry) {
	*out = *in
	if in.AllowedUsages != nil {
		in, out := &in.AllowedUsages, &out.AllowedUsages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedIdentityEntry.
func (in *ManagedIdentityEntry) DeepCopy() *ManagedIdentityEntry {
	if in == nil {
		return nil
	}
	out := new(ManagedIdentityEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedIdentityPolicy) DeepCopyInto(out *ManagedIdentityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedIdentityPolicy.
func (in *ManagedIdentityPolicy) DeepCopy() *ManagedIdentityPolicy {
	if in == nil {
		return nil
	}
	out := new(ManagedIdentityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedIdentityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedIdentityPolicyList) DeepCopyInto(out *ManagedIdentityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedIdentityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedIdentityPolicyList.
func (in *ManagedIdentityPolicyList) DeepCopy() *ManagedIdentityPolicyList {
	if in == nil {
		return nil
	}
	out := new(ManagedIdentityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedIdentityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedIdentityPolicyParameters) DeepCopyInto(out *ManagedIdentityPolicyParameters) {
	*out = *in
	in.PolicyTarget.DeepCopyInto(&out.PolicyTarget)
	if in.Identities != nil {
		in, out := &in.Identities, &out.Identities
		*out = make([]ManagedIdentityEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedIdentityPolicyParameters.
func (in *ManagedIdentityPolicyParameters) DeepCopy() *ManagedIdentityPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(ManagedIdentityPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedIdentityPolicySpec) DeepCopyInto(out *ManagedIdentityPolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedIdentityPolicySpec.
func (in *ManagedIdentityPolicySpec) DeepCopy() *ManagedIdentityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ManagedIdentityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedIdentityPolicyStatus) DeepCopyInto(out *ManagedIdentityPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedIdentityPolicyStatus.
func (in *ManagedIdentityPolicyStatus) DeepCopy() *ManagedIdentityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedIdentityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeLookback) DeepCopyInto(out *MergeLookback) {
	*out = *in
	if in.CustomPeriod != nil {
		in, out := &in.CustomPeriod, &out.CustomPeriod
		*out = new(common.Timespan)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeLookback.
func (in *MergeLookback) DeepCopy() *MergeLookback {
	if in == nil {
		return nil
	}
	out := new(MergeLookback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergePolicy) DeepCopyInto(out *MergePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergePolicy.
func (in *MergePolicy) DeepCopy() *MergePolicy {
	if in == nil {
		return nil
	}
	out := new(MergePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MergePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergePolicyList) DeepCopyInto(out *MergePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MergePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergePolicyList.
func (in *MergePolicyList) DeepCopy() *MergePolicyList {
	if in == nil {
		return nil
	}
	out := new(MergePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MergePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergePolicyParameters) DeepCopyInto(out *MergePolicyParameters) {
	*out = *in
	in.PolicyTarget.DeepCopyInto(&out.PolicyTarget)
	if in.RowCountUpperBoundForMerge != nil {
		in, out := &in.RowCountUpperBoundForMerge, &out.RowCountUpperBoundForMerge
		*out = new(int64)
		**out = **in
	}
	if in.OriginalSizeMBUpperBoundForMerge != nil {
		in, out := &in.OriginalSizeMBUpperBoundForMerge, &out.OriginalSizeMBUpperBoundForMerge
		*out = new(int64)
		**out = **in
	}
	if in.MaxExtentsToMerge != nil {
		in, out := &in.MaxExtentsToMerge, &out.MaxExtentsToMerge
		*out = new(int64)
		**out = **in
	}
	if in.MaxRangeInHours != nil {
		in, out := &in.MaxRangeInHours, &out.MaxRangeInHours
		*out = new(int64)
		**out = **in
	}
	if in.AllowRebuild != nil {
		in, out := &in.AllowRebuild, &out.AllowRebuild
		*out = new(bool)
		**out = **in
	}
	if in.AllowMerge != nil {
		in, out := &in.AllowMerge, &out.AllowMerge
		*out = new(bool)
		**out = **in
	}
	if in.Lookback != nil {
		in, out := &in.Lookback, &out.Lookback
		*out = new(MergeLookback)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergePolicyParameters.
func (in *MergePolicyParameters) DeepCopy() *MergePolicyParameters {
	if in == nil {
		return nil
	}
	out := new(MergePolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergePolicySpec) DeepCopyInto(out *MergePolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergePolicySpec.
func (in *MergePolicySpec) DeepCopy() *MergePolicySpec {
	if in == nil {
		return nil
	}
	out := new(MergePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergePolicyStatus) DeepCopyInto(out *MergePolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergePolicyStatus.
func (in *MergePolicyStatus) DeepCopy() *MergePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(MergePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartitionKey) DeepCopyInto(out *PartitionKey) {
	*out = *in
	in.Properties.DeepCopyInto(&out.Properties)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartitionKey.
func (in *PartitionKey) DeepCopy() *PartitionKey {
	if in == nil {
		return nil
	}
	out := new(PartitionKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartitionKeyProperties) DeepCopyInto(out *PartitionKeyProperties) {
	*out = *in
	if in.Function != nil {
		in, out := &in.Function, &out.Function
		*out = new(string)
		**out = **in
	}
	if in.MaxPartitionCount != nil {
		in, out := &in.MaxPartitionCount, &out.MaxPartitionCount
		*out = new(int64)
		**out = **in
	}
	if in.Seed != nil {
		in, out := &in.Seed, &out.Seed
		*out = new(int64)
		**out = **in
	}
	if in.PartitionAssignmentMode != nil {
		in, out := &in.PartitionAssignmentMode, &out.PartitionAssignmentMode
		*out = new(string)
		**out = **in
	}
	if in.Reference != nil {
		in, out := &in.Reference, &out.Reference
		*out = new(string)
		**out = **in
	}
	if in.RangeSize != nil {
		in, out := &in.RangeSize, &out.RangeSize
		*out = new(common.Timespan)
		**out = **in
	}
	if in.OverrideCreationTime != nil {
		in, out := &in.OverrideCreationTime, &out.OverrideCreationTime
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartitionKeyProperties.
func (in *PartitionKeyProperties) DeepCopy() *PartitionKeyProperties {
	if in == nil {
		return nil
	}
	out := new(PartitionKeyProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartitioningPolicy) DeepCopyInto(out *PartitioningPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartitioningPolicy.
func (in *PartitioningPolicy) DeepCopy() *PartitioningPolicy {
	if in == nil {
		return nil
	}
	out := new(PartitioningPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PartitioningPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartitioningPolicyList) DeepCopyInto(out *PartitioningPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PartitioningPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartitioningPolicyList.
func (in *PartitioningPolicyList) DeepCopy() *PartitioningPolicyList {
	if in == nil {
		return nil
	}
	out := new(PartitioningPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PartitioningPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartitioningPolicyParameters) DeepCopyInto(out *PartitioningPolicyParameters) {
	*out = *in
	in.PolicyTarget.DeepCopyInto(&out.PolicyTarget)
	if in.PartitionKeys != nil {
		in, out := &in.PartitionKeys, &out.PartitionKeys
		*out = make([]PartitionKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EffectiveDateTime != nil {
		in, out := &in.EffectiveDateTime, &out.EffectiveDateTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartitioningPolicyParameters.
func (in *PartitioningPolicyParameters) DeepCopy() *PartitioningPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(PartitioningPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartitioningPolicySpec) DeepCopyInto(out *PartitioningPolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartitioningPolicySpec.
func (in *PartitioningPolicySpec) DeepCopy() *PartitioningPolicySpec {
	if in == nil {
		return nil
	}
	out := new(PartitioningPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartitioningPolicyStatus) DeepCopyInto(out *PartitioningPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartitioningPolicyStatus.
func (in *PartitioningPolicyStatus) DeepCopy() *PartitioningPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PartitioningPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyObservation) DeepCopyInto(out *PolicyObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyObservation.
func (in *PolicyObservation) DeepCopy() *PolicyObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyTarget) DeepCopyInto(out *PolicyTarget) {
	*out = *in
	in.Entity.DeepCopyInto(&out.Entity)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyTarget.
func (in *PolicyTarget) DeepCopy() *PolicyTarget {
	if in == nil {
		return nil
	}
	out := new(PolicyTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryAccelerationPolicy) DeepCopyInto(out *QueryAccelerationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryAccelerationPolicy.
func (in *QueryAccelerationPolicy) DeepCopy() *QueryAccelerationPolicy {
	if in == nil {
		return nil
	}
	out := new(QueryAccelerationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueryAccelerationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryAccelerationPolicyList) DeepCopyInto(out *QueryAccelerationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QueryAccelerationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryAccelerationPolicyList.
func (in *QueryAccelerationPolicyList) DeepCopy() *QueryAccelerationPolicyList {
	if in == nil {
		return nil
	}
	out := new(QueryAccelerationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueryAccelerationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryAccelerationPolicyParameters) DeepCopyInto(out *QueryAccelerationPolicyParameters) {
	*out = *in
	in.PolicyTarget.DeepCopyInto(&out.PolicyTarget)
	if in.Hot != nil {
		in, out := &in.Hot, &out.Hot
		*out = new(common.Timespan)
		**out = **in
	}
	if in.MaxAge != nil {
		in, out := &in.MaxAge, &out.MaxAge
		*out = new(common.Timespan)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryAccelerationPolicyParameters.
func (in *QueryAccelerationPolicyParameters) DeepCopy() *QueryAccelerationPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(QueryAccelerationPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryAccelerationPolicySpec) DeepCopyInto(out *QueryAccelerationPolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryAccelerationPolicySpec.
func (in *QueryAccelerationPolicySpec) DeepCopy() *QueryAccelerationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(QueryAccelerationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryAccelerationPolicyStatus) DeepCopyInto(out *QueryAccelerationPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryAccelerationPolicyStatus.
func (in *QueryAccelerationPolicyStatus) DeepCopy() *QueryAccelerationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(QueryAccelerationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestrictedViewAccessPolicy) DeepCopyInto(out *RestrictedViewAccessPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestrictedViewAccessPolicy.
func (in *RestrictedViewAccessPolicy) DeepCopy() *RestrictedViewAccessPolicy {
	if in == nil {
		return nil
	}
	out := new(RestrictedViewAccessPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RestrictedViewAccessPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestrictedViewAccessPolicyList) DeepCopyInto(out *RestrictedViewAccessPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RestrictedViewAccessPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestrictedViewAccessPolicyList.
func (in *RestrictedViewAccessPolicyList) DeepCopy() *RestrictedViewAccessPolicyList {
	if in == nil {
		return nil
	}
	out := new(RestrictedViewAccessPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RestrictedViewAccessPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestrictedViewAccessPolicyParameters) DeepCopyInto(out *RestrictedViewAccessPolicyParameters) {
	*out = *in
	in.PolicyTarget.DeepCopyInto(&out.PolicyTarget)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestrictedViewAccessPolicyParameters.
func (in *RestrictedViewAccessPolicyParameters) DeepCopy() *RestrictedViewAccessPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(RestrictedViewAccessPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestrictedViewAccessPolicySpec) DeepCopyInto(out *RestrictedViewAccessPolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestrictedViewAccessPolicySpec.
func (in *RestrictedViewAccessPolicySpec) DeepCopy() *RestrictedViewAccessPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RestrictedViewAccessPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestrictedViewAccessPolicyStatus) DeepCopyInto(out *RestrictedViewAccessPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestrictedViewAccessPolicyStatus.
func (in *RestrictedViewAccessPolicyStatus) DeepCopy() *RestrictedViewAccessPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RestrictedViewAccessPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicy) DeepCopyInto(out *RetentionPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicy.
func (in *RetentionPolicy) DeepCopy() *RetentionPolicy {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RetentionPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicyList) DeepCopyInto(out *RetentionPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RetentionPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicyList.
func (in *RetentionPolicyList) DeepCopy() *RetentionPolicyList {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RetentionPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicyParameters) DeepCopyInto(out *RetentionPolicyParameters) {
	*out = *in
	in.PolicyTarget.DeepCopyInto(&out.PolicyTarget)
	if in.SoftDeletePeriod != nil {
		in, out := &in.SoftDeletePeriod, &out.SoftDeletePeriod
		*out = new(common.Timespan)
		**out = **in
	}
	if in.Recoverability != nil {
		in, out := &in.Recoverability, &out.Recoverability
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicyParameters.
func (in *RetentionPolicyParameters) DeepCopy() *RetentionPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicySpec) DeepCopyInto(out *RetentionPolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicySpec.
func (in *RetentionPolicySpec) DeepCopy() *RetentionPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicyStatus) DeepCopyInto(out *RetentionPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicyStatus.
func (in *RetentionPolicyStatus) DeepCopy() *RetentionPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowLevelSecurityPolicy) DeepCopyInto(out *RowLevelSecurityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowLevelSecurityPolicy.
func (in *RowLevelSecurityPolicy) DeepCopy() *RowLevelSecurityPolicy {
	if in == nil {
		return nil
	}
	out := new(RowLevelSecurityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RowLevelSecurityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowLevelSecurityPolicyList) DeepCopyInto(out *RowLevelSecurityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RowLevelSecurityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowLevelSecurityPolicyList.
func (in *RowLevelSecurityPolicyList) DeepCopy() *RowLevelSecurityPolicyList {
	if in == nil {
		return nil
	}
	out := new(RowLevelSecurityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RowLevelSecurityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowLevelSecurityPolicyParameters) DeepCopyInto(out *RowLevelSecurityPolicyParameters) {
	*out = *in
	in.PolicyTarget.DeepCopyInto(&out.PolicyTarget)
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowLevelSecurityPolicyParameters.
func (in *RowLevelSecurityPolicyParameters) DeepCopy() *RowLevelSecurityPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(RowLevelSecurityPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowLevelSecurityPolicySpec) DeepCopyInto(out *RowLevelSecurityPolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowLevelSecurityPolicySpec.
func (in *RowLevelSecurityPolicySpec) DeepCopy() *RowLevelSecurityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RowLevelSecurityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowLevelSecurityPolicyStatus) DeepCopyInto(out *RowLevelSecurityPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowLevelSecurityPolicyStatus.
func (in *RowLevelSecurityPolicyStatus) DeepCopy() *RowLevelSecurityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RowLevelSecurityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowOrderColumn) DeepCopyInto(out *RowOrderColumn) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowOrderColumn.
func (in *RowOrderColumn) DeepCopy() *RowOrderColumn {
	if in == nil {
		return nil
	}
	out := new(RowOrderColumn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowOrderPolicy) DeepCopyInto(out *RowOrderPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowOrderPolicy.
func (in *RowOrderPolicy) DeepCopy() *RowOrderPolicy {
	if in == nil {
		return nil
	}
	out := new(RowOrderPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RowOrderPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowOrderPolicyList) DeepCopyInto(out *RowOrderPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RowOrderPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowOrderPolicyList.
func (in *RowOrderPolicyList) DeepCopy() *RowOrderPolicyList {
	if in == nil {
		return nil
	}
	out := new(RowOrderPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RowOrderPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowOrderPolicyParameters) DeepCopyInto(out *RowOrderPolicyParameters) {
	*out = *in
	in.PolicyTarget.DeepCopyInto(&out.PolicyTarget)
	if in.Columns != nil {
		in, out := &in.Columns, &out.Columns
		*out = make([]RowOrderColumn, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowOrderPolicyParameters.
func (in *RowOrderPolicyParameters) DeepCopy() *RowOrderPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(RowOrderPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowOrderPolicySpec) DeepCopyInto(out *RowOrderPolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowOrderPolicySpec.
func (in *RowOrderPolicySpec) DeepCopy() *RowOrderPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RowOrderPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowOrderPolicyStatus) DeepCopyInto(out *RowOrderPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowOrderPolicyStatus.
func (in *RowOrderPolicyStatus) DeepCopy() *RowOrderPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RowOrderPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardingPolicy) DeepCopyInto(out *ShardingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardingPolicy.
func (in *ShardingPolicy) DeepCopy() *ShardingPolicy {
	if in == nil {
		return nil
	}
	out := new(ShardingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShardingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardingPolicyList) DeepCopyInto(out *ShardingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShardingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardingPolicyList.
func (in *ShardingPolicyList) DeepCopy() *ShardingPolicyList {
	if in == nil {
		return nil
	}
	out := new(ShardingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShardingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardingPolicyParameters) DeepCopyInto(out *ShardingPolicyParameters) {
	*out = *in
	in.PolicyTarget.DeepCopyInto(&out.PolicyTarget)
	if in.ShardEngineMaxRowCount != nil {
		in, out := &in.ShardEngineMaxRowCount, &out.ShardEngineMaxRowCount
		*out = new(int64)
		**out = **in
	}
	if in.ShardEngineMaxExtentSizeInMb != nil {
		in, out := &in.ShardEngineMaxExtentSizeInMb, &out.ShardEngineMaxExtentSizeInMb
		*out = new(int64)
		**out = **in
	}
	if in.ShardEngineMaxOriginalSizeInMb != nil {
		in, out := &in.ShardEngineMaxOriginalSizeInMb, &out.ShardEngineMaxOriginalSizeInMb
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardingPolicyParameters.
func (in *ShardingPolicyParameters) DeepCopy() *ShardingPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(ShardingPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardingPolicySpec) DeepCopyInto(out *ShardingPolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardingPolicySpec.
func (in *ShardingPolicySpec) DeepCopy() *ShardingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ShardingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardingPolicyStatus) DeepCopyInto(out *ShardingPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardingPolicyStatus.
func (in *ShardingPolicyStatus) DeepCopy() *ShardingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ShardingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamingIngestionPolicy) DeepCopyInto(out *StreamingIngestionPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamingIngestionPolicy.
func (in *StreamingIngestionPolicy) DeepCopy() *StreamingIngestionPolicy {
	if in == nil {
		return nil
	}
	out := new(StreamingIngestionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StreamingIngestionPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamingIngestionPolicyList) DeepCopyInto(out *StreamingIngestionPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StreamingIngestionPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamingIngestionPolicyList.
func (in *StreamingIngestionPolicyList) DeepCopy() *StreamingIngestionPolicyList {
	if in == nil {
		return nil
	}
	out := new(StreamingIngestionPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StreamingIngestionPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamingIngestionPolicyParameters) DeepCopyInto(out *StreamingIngestionPolicyParameters) {
	*out = *in
	in.PolicyTarget.DeepCopyInto(&out.PolicyTarget)
	if in.HintAllocatedRate != nil {
		in, out := &in.HintAllocatedRate, &out.HintAllocatedRate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamingIngestionPolicyParameters.
func (in *StreamingIngestionPolicyParameters) DeepCopy() *StreamingIngestionPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(StreamingIngestionPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamingIngestionPolicySpec) DeepCopyInto(out *StreamingIngestionPolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamingIngestionPolicySpec.
func (in *StreamingIngestionPolicySpec) DeepCopy() *StreamingIngestionPolicySpec {
	if in == nil {
		return nil
	}
	out := new(StreamingIngestionPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamingIngestionPolicyStatus) DeepCopyInto(out *StreamingIngestionPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamingIngestionPolicyStatus.
func (in *StreamingIngestionPolicyStatus) DeepCopy() *StreamingIngestionPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(StreamingIngestionPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdatePolicy) DeepCopyInto(out *UpdatePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdatePolicy.
func (in *UpdatePolicy) DeepCopy() *UpdatePolicy {
	if in == nil {
		return nil
	}
	out := new(UpdatePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpdatePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdatePolicyEntry) DeepCopyInto(out *UpdatePolicyEntry) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.SourceRef != nil {
		in, out := &in.SourceRef, &out.SourceRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.SourceSelector != nil {
		in, out := &in.SourceSelector, &out.SourceSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Transactional != nil {
		in, out := &in.Transactional, &out.Transactional
		*out = new(bool)
		**out = **in
	}
	if in.PropagateIngestionProperties != nil {
		in, out := &in.PropagateIngestionProperties, &out.PropagateIngestionProperties
		*out = new(bool)
		**out = **in
	}
	if in.ManagedIdentity != nil {
		in, out := &in.ManagedIdentity, &out.ManagedIdentity
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdatePolicyEntry.
func (in *UpdatePolicyEntry) DeepCopy() *UpdatePolicyEntry {
	if in == nil {
		return nil
	}
	out := new(UpdatePolicyEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdatePolicyList) DeepCopyInto(out *UpdatePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UpdatePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdatePolicyList.
func (in *UpdatePolicyList) DeepCopy() *UpdatePolicyList {
	if in == nil {
		return nil
	}
	out := new(UpdatePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpdatePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdatePolicyParameters) DeepCopyInto(out *UpdatePolicyParameters) {
	*out = *in
	in.PolicyTarget.DeepCopyInto(&out.PolicyTarget)
	if in.Updates != nil {
		in, out := &in.Updates, &out.Updates
		*out = make([]UpdatePolicyEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdatePolicyParameters.
func (in *UpdatePolicyParameters) DeepCopy() *UpdatePolicyParameters {
	if in == nil {
		return nil
	}
	out := new(UpdatePolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdatePolicySpec) DeepCopyInto(out *UpdatePolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdatePolicySpec.
func (in *UpdatePolicySpec) DeepCopy() *UpdatePolicySpec {
	if in == nil {
		return nil
	}
	out := new(UpdatePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdatePolicyStatus) DeepCopyInto(out *UpdatePolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdatePolicyStatus.
func (in *UpdatePolicyStatus) DeepCopy() *UpdatePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(UpdatePolicyStatus)
	in.DeepCopyInto(out)
	return out
}
