// SPDX-FileCopyrightText: 2026 The provider-azure-adx Authors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this ContinuousExport.
func (mg *ContinuousExport) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.ExternalTable,
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ExternalTableRef,
		Selector:     mg.Spec.ForProvider.ExternalTableSelector,
		To: reference.To{
			List:    &ExternalTableList{},
			Managed: &ExternalTable{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ExternalTable")
	}
	mg.Spec.ForProvider.ExternalTable = rsp.ResolvedValue
	mg.Spec.ForProvider.ExternalTableRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: mg.Spec.ForProvider.OverTables,
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.OverTablesRefs,
		Selector:      mg.Spec.ForProvider.OverTablesSelector,
		To: reference.To{
			List:    &TableList{},
			Managed: &Table{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.OverTables")
	}
	mg.Spec.ForProvider.OverTables = mrsp.ResolvedValues
	mg.Spec.ForProvider.OverTablesRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this IngestionMapping.
func (mg *IngestionMapping) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.Table,
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.TableRef,
		Selector:     mg.Spec.ForProvider.TableSelector,
		To: reference.To{
			List:    &TableList{},
			Managed: &Table{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Table")
	}
	mg.Spec.ForProvider.Table = rsp.ResolvedValue
	mg.Spec.ForProvider.TableRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this MaterializedView.
func (mg *MaterializedView) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SourceTable),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.SourceTableRef,
		Selector:     mg.Spec.ForProvider.SourceTableSelector,
		To: reference.To{
			List:    &TableList{},
			Managed: &Table{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SourceTable")
	}
	mg.Spec.ForProvider.SourceTable = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SourceTableRef = rsp.ResolvedReference

	return nil
}
